<a href="https://colab.research.google.com/github/khalilAdewole/DIMO-Assessment/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Reference
Resource notebook : https://www.learnpytorch.io/00_pytorch_fundamentals/


For Questions : https://github.com/mrdbourke/pytorch-deep-learning/discussions


In [26]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [27]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.5.1+cu124


## Introduction to Tensors

### Creating Tensors

In [28]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [29]:
scalar.ndim

0

In [30]:
# get tensor back as Python int

scalar.item()

7

In [31]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [32]:
vector.ndim

1

In [33]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX


tensor([[ 7,  8],
        [ 9, 10]])

In [34]:
MATRIX.ndim

MATRIX.shape

torch.Size([2, 2])

In [35]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [36]:
TENSOR.ndim

TENSOR.shape

torch.Size([1, 3, 3])

## Random Tensors

In [37]:
## Creating Random Tensors

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.5479, 0.9255, 0.2500, 0.9324],
        [0.0032, 0.6156, 0.0029, 0.2334],
        [0.2600, 0.2537, 0.2390, 0.2791]])

In [38]:
## Create a random tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(size=(224,224,3)) # height, width, color channels
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

###Zeros and Ones

In [39]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [40]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [41]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Creating a range of tensors and tensors-like

In [42]:
# Use torch.arange()
one_to_twenty = torch.arange(start=1,end=21, step = 1)
one_to_twenty

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20])

In [43]:
ten_zeros = torch.zeros_like(input=one_to_twenty)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [44]:
ten_ones = torch.ones_like(input=one_to_twenty)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

###Tensor Datatypes

In [52]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None, # what datatype is the tensor (e.g. float32 or float16)
                               device=None, # what device is your tensor on
                               requires_grad=False) # whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [53]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor


tensor([3., 6., 9.], dtype=torch.float16)

In [54]:
tensor_multiply = float_32_tensor * float_16_tensor
tensor_multiply

tensor([ 9., 36., 81.])

In [56]:
tensor_multiply.dtype

torch.float32

##Getting information about tensor attributes

In [57]:
some_tensors = torch.rand(3,4)
some_tensors

tensor([[0.9760, 0.7366, 0.4216, 0.3254],
        [0.4710, 0.8967, 0.8184, 0.5817],
        [0.1025, 0.0119, 0.4366, 0.9756]])

In [59]:
print (f"Datatype of tensor: {some_tensors.dtype}")
print (f"Shape of tensor: {some_tensors.shape}")
print (f"Device tensor is on: {some_tensors.device}")

Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


In [61]:
tensor = torch.tensor([1,2,3])
tensor

tensor([1, 2, 3])

## Matrix Multiplication

In [68]:
%%time
value = 0
for i in range (len(tensor)):
  value += tensor[i]
print(value)

tensor(6)
CPU times: user 2.92 ms, sys: 0 ns, total: 2.92 ms
Wall time: 2.82 ms


In [64]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 802 µs, sys: 50 µs, total: 852 µs
Wall time: 679 µs


tensor(14)

In [69]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [71]:
output = torch.mm(tensor_A.T, tensor_B)
output

tensor([[ 76, 103],
        [100, 136]])

In [73]:
x = torch.arange (0,100,10)

x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [74]:
torch.sum(x)

tensor(450)

In [78]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [79]:
x.argmin()

tensor(0)

In [80]:
x.argmax()

tensor(9)

In [81]:
x[9]

tensor(90)